// Canonical ordered poem list — matches the index page order.
// Add new poems here; prev/next nav is derived automatically.
window.POEMS = [
  // English — Free Verse
  { slug: 'tale-of-wandering-poet',      title: 'Tale of the Wandering Poet' },
  { slug: 'hairpin',                     title: 'The Hairpin' },
  { slug: 'in-the-rain',                 title: 'In the Rain' },
  { slug: 'september',                   title: 'September' },
  { slug: 'a-ring-in-the-rain',          title: 'A Ring in the Rain' },
  { slug: 'jessie',                      title: 'Jessie' },
  { slug: 'does-the-rain-ever-fall',     title: 'Does the Rain Ever Fall on Us' },
  { slug: 'lost-at-sea',                 title: 'Lost at Sea' },
  { slug: 'almost-blue',                 title: 'Almost Blue' },
  { slug: 'eyes-almost-blue',            title: 'Eyes Almost Blue' },
  { slug: 'once-more',                   title: 'Once More' },
  { slug: 'eleventh-of-april',           title: '11th of April' },
  { slug: 'simple-twist-of-fate',        title: 'Simple Twist of Fate' },
  { slug: 'cafe-in-march',               title: 'The Café in March' },
  { slug: 'only-the-garden-roses',       title: 'Only the Garden Roses Were Listening' },
  // English — Anaphoric Verse
  { slug: 'it-not-as-if',               title: "It's Not As If" },
  { slug: 'regret',                      title: 'Regret' },
  { slug: 'once-again',                  title: 'Once Again' },
  // English — Lyric Ode
  { slug: 'my-dear-melancholy',          title: 'My Dear Melancholy' },
  // English — Prose Poem
  { slug: 'gazing-at-flowers',           title: 'Gazing at Flowers' },
  { slug: 'a-wandering-taxi',            title: 'A Wandering Taxi' },
  // English — Narrative Verse
  { slug: 'at-the-turn-of-a-hill',      title: 'At the Turn of a Hill' },
  { slug: 'girl-with-cat-named-whiskey', title: 'The Girl with a Cat Named Whiskey' },
  { slug: 'tokyo',                       title: 'Tokyo' },
  { slug: 'the-woman-who-brought-spring', title: 'The Woman Who Brought Spring' },
  { slug: 'the-wardens-garden',          title: "The Warden's Garden" },
  { slug: 'the-tattered-page',           title: 'The Tattered Page' },
  { slug: 'the-blue-scarf',              title: 'The Blue Scarf' },
  { slug: 'a-beautiful-curse',           title: 'A Beautiful Curse' },
  // English — Rhymed Verse · ABAB
  { slug: 'empty-reasons',              title: 'Empty Reasons' },
  { slug: 'after-many-seasons',         title: 'After Many Seasons' },
  { slug: 'red-sweater',                title: 'Red Sweater' },
  { slug: 'almeres-fair',               title: "Almere's Fair" },
  { slug: 'the-bar-under-a-lonely-star', title: 'The Bar Under a Lonely Star' },
  { slug: 'homeward-bound',             title: 'Homeward Bound' },
  { slug: 'a-rainy-day-of-july',        title: 'A Rainy Day of July' },
  { slug: 'the-gardner',                title: 'The Gardner' },
  { slug: 'the-green-umbrella',         title: 'The Green Umbrella' },
  { slug: 'painting-her',               title: 'Painting Her' },
  { slug: 'ive-known-life',             title: "I've Known Life" },
  { slug: 'dusky-window',               title: 'Dusky Window' },
  { slug: 'before-we-grey',             title: 'Before We Grey' },
  // English — Waka
  { slug: 'garden-of-words',            title: 'Garden of Words' },
  // Hindi · Urdu — Ghazal
  { slug: 'saboot',                     title: 'Saboot' },
  { slug: 'dariya',                     title: 'Dariya' },
  { slug: 'hum-kahan-jayenge',          title: 'Hum Kahan Jayenge' },
  { slug: 'kuch-lafz',                  title: 'Kuch Lafz' },
  { slug: 'door-jaake-basi',            title: 'Door Jaake Basi' },
  { slug: 'shayad',                     title: 'Shayad' },
  { slug: 'jaayega-kahan-ab',           title: 'Jaayega Kahan Ab' },
  { slug: 'hawa-ke-dastaan',            title: 'Hawa Ke Dastaan' },
  { slug: 'udaasi-ka-itiraf',           title: 'Udaasi Ka Itiraf' },
  { slug: 'khaali-gali',                title: 'Khaali Gali' },
  { slug: 'intezaar',                   title: 'Intezaar' },
  { slug: 'sardi-ka-mahina',            title: 'Sardi Ka Mahina' },
  // Hindi · Urdu — Nazm
  { slug: 'shaam-e-gham',              title: 'Shaam-e-Gham' },
  { slug: 'tumhari-yaadein',           title: 'तुम्हारी यादें' },
  { slug: 'pehele-aur-fir',            title: 'Pehele Aur Fir' },
  { slug: 'shaam-samay',               title: 'Shaam Samay' },
  { slug: 'aangan-ke-phool',           title: 'Aangan Ke Phool' },
  { slug: 'naya-rang',                 title: 'Naya Rang' },
  { slug: 'anjaan-sheher',             title: 'Anjaan Sheher' },
  { slug: 'jaan-e-baharan',            title: 'Jaan-e-Baharan' },
  { slug: 'ghaav-ki-khushboo',         title: 'Ghaav Ki Khushboo' },
  { slug: 'bekashi-ka-saya',           title: 'Bekashi Ka Saya' },
  { slug: 'aadat',                     title: 'Aadat' },
  { slug: 'khawab-ki-dakhili',         title: 'Khawab Ki Dakhili' },
  { slug: 'patjhad-ka-parichay',       title: 'Patjhad Ka Parichay' },
  // Hindi · Urdu — Nathar Nazm
  { slug: 'jhuti-tasalli',             title: 'Jhuti Tasalli' },
];
